version: '2'

services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: example
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ./redmine/usr-src-redmine-files:/usr/src/redmine/files


  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./mariadb/var-lib-mysql/:/var/lib/mysql
