version: '2'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql


  # Redmine Application
  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: root_password
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ./redmine/files:/usr/src/redmine/files


  # Wordpress Application
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      MARIADB_PASSWORD: root_password
    volumes:
      - ./wordpress/wordpress-data:/bitnami/wordpress
      - ./wordpress/apache-data:/bitnami/apache
      - ./wordpress/php-data:/bitnami/php


  # ownCloud Application
  owncloud:
    image: owncloud
    container_name: owncloud
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8181:80
    volumes:
      - ./owncloud/owncloud-data:/var/www/html/data
      - ./owncloud/owncloud-config:/var/www/html/config
      - ./owncloud/owncloud-apps:/var/www/html/apps2


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
       - PMA_HOSTS=mariadb
      restart: always
      ports:
       - 8081:80
