# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '2'

services:

  owncloud:
    image: owncloud
    restart: always
    depends_on:
      - owncloud-mariadb
    ports:
      - 8080:80
    volumes:
      - ./owncloud/owncloud-data:/var/www/html/data
      - ./owncloud/owncloud-config:/var/www/html/config
      - ./owncloud/owncloud-apps:/var/www/html/apps2

  owncloud-mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mariadb/var-lib-mysql/:/var/lib/mysql
